build:
  stage: build
  image: 
    name: registry.gitlab.com/gitlab-ci-utils/container-images/kaniko:debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination your-image:tag