-- Curated list of known/trusted scanlation group names (for Tier 2 scoring).
-- Names are matched case-insensitively at score time.
CREATE TABLE IF NOT EXISTS TrustedGroup (
    name TEXT PRIMARY KEY  -- exact group name as it appears in scanlator_group
);

-- Populate groups
INSERT OR IGNORE INTO TrustedGroup (name) VALUES
('/A/nimango Scans'),
('/ak/ Scans'),
('Agents of Change'),
('Albedo'),
('Alpha Beta Kappa'),
('Aoitenshi'),
('Aqua Scans'),
('Aquarium Tourmaline'),
('Arite Drop'),
('Atelier du Noi'),
('Pair of 2+'),
('Apollo Team'),
('Arang Scans'),
('Astral Valley Scans'),
('Asura Scans'),
('Black Cat Scans'),
('Blue Sterling Scans'),
('Boredom Society Scans'),
('Chibi Manga'),
('Chillock Scans'),
('Cygnet Scans'),
('Death Toll Scans'),
('Disaster Scans'),
('#Dropout'),
('Edelgarde Scans'),
('Eidetic Memo Scans'),
('#EverydayHeroes Scans'),
('Fallen Angels Scans'),
('Fe Scans'),
('Fire Syndicate'),
('Flame Scans'),
('Flightless Bird Scans'),
('Galaxy Degen Scans'),
('Gemelli Scans'),
('Gourmet Scans'),
('Hachirumi Scans'),
('Harmless Monsters'),
('Hatigarm Scans'),
('Heroz Scans'),
('Hi Wa Mata Noboru'),
('Hokuto No Gun'),
('Hunlight Scans'),
('Immortal Updates'),
('Infrequent Scans'),
('Japanese Unloved Manga'),
('JUM'),
('JoJo''s Colored Adventure Team'),
('Kirei Cake'),
('KS Group'),
('Kyakka Scans'),
('Leviatan Scans'),
('LH Translation'),
('Little Miss & Good Sir Scans'),
('LM&GS'),
('Lovesick Alley'),
('lowercase e'),
('Lumine Scans'),
('Lynx Scans'),
('Manga Great'),
('Aloalivn'),
('Manga Sushi'),
('Manga SY'),
('Manhua Plus'),
('Maru Scans'),
('Megchan''s Scanlations'),
('Meraki Scans'),
('Method Scans'),
('Misfits Scans'),
('MMScans'),
('Moe and Friends'),
('Mono Scans'),
('Mystical Merries Scans'),
('NANI? Scans'),
('Not A Scanlation Scans'),
('NASS'),
('Painful Nightz Scans'),
('Peerless Dad Scans'),
('PMScans'),
('Purple Cress'),
('Quick Sand Scans'),
('QSS'),
('Rain of Snow Scans'),
('Ramyun Scans'),
('Random Scans'),
('Reaper Scans'),
('Renascence Scans'),
('Renascans'),
('Reset Scans'),
('Roselia Scanlations'),
('SAWTEAM'),
('Sense Scans'),
('Shadow Madness'),
('Silent Sky Scans'),
('Sleeping Knight'),
('SK'),
('Sleepless Society'),
('Slug Chicks Scans'),
('Speedcat Scans'),
('Spring Palette'),
('Tanooki'),
('TeruTeru Scans'),
('The Guild'),
('The Nonames Scans'),
('TimelessLeaf'),
('Tonari No Scanlation'),
('TOOR Scans'),
('Tritinia Scans'),
('Tsundere Service Providers'),
('TSP'),
('Twilight Scans'),
('Twisted Hel Scans'),
('Un Team A Caso'),
('Vanguard'),
('Volkan Scans'),
('XuN Scans'),
('Zaibatsu Scans'),
('Zero Scans'),
('BangAQUA'),
('BAP Scans'),
('Beika Street Irregulars'),
('Biamam'),
('Megane Scans'),
('Black Hand Scans'),
('BlastComic Scans'),
('BloodL'),
('Bubble Tea Scans'),
('Café Scanlations'),
('Cafe Scanlations'),
('Cash Money Chiyo'),
('CAT Scans'),
('Champion Scans'),
('ChaosTeam'),
('Cheese Scans'),
('Chibi Manga'),
('Comicola Fansub');